apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: session10-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment-web
  template:
    metadata:
      labels:
        app: deployment-web
        version: v1
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
