apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: session10-demo
  labels:
    app: web-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
