apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-replicaset
  namespace: session10-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: replica-web
  template:
    metadata:
      labels:
        app: replica-web
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
