apiVersion: v1
kind: Service
metadata:
  name: rolling-service
  namespace: session10-demo
spec:
  type: NodePort
  selector:
    app: deployment-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
