apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
  namespace: session10-demo
spec:
  type: NodePort
  selector:
    app: blue-green-demo
    slot: blue
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30020
