apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-data
  namespace: session13-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 200Mi
