apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-data
  namespace: session13-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 500Mi
