apiVersion: v1
kind: Pod
metadata:
  name: nginx-basics
  namespace: session9-demo
  labels:
    app: nginx-basics
spec:
  containers:
    - name: nginx
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
